version: "3.8"
services:
  db:
    image: postgres:16.1
    container_name: db_app
#    command: -p 5430
#    expose:
#      - 5431
    environment:
      POSTGRES_PASSWORD: rootroot
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
